### ISSUE TITLE
0pdd bot

### ISSUE THREAD

**Issue by includealex** [polystat/j2eo#163]
I think that adding [0pdd](https://github.com/yegor256/0pdd) bot to j2eo project would be helpful.

**Comment by includealex** [comment]
@yegor256 what do you think about it?

**Comment by yegor256** [comment]
@includealex it's already here, just use it

**Comment by yegor256** [comment]
@includealex there is an error in the code: https://github.com/polystat/j2eo/commit/45010b09198e6b7acd7551bfee0798f0a268c360#comments
